# Generated by Django 4.0.5 on 2022-07-07 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Enter a task to add to the list ...')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('done_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
